# This is a basic workflow to help you get started with Actions

name: Syncing Testing Between 2 Independent Repos
#Thanks to https://github.com/marketplace/actions/github-repo-sync (need to figure out how to cite, use properly)
#https://github.com/marketplace/actions/github-repo-sync
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
#Test Add
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v2
      with:
        source_repo: "https://github.com/vspenubarthi/SyncTesting_1.git"
        source_branch: "master"
        destination_repo: "git@github.com:vspenubarthi/SyncTesting_2.git"
        destination_branch: "master"
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
  # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#     - uses: actions/checkout@v2
      
#     - name: Git Sync Action
#     - uses: wei/git-sync@v2.0.0


#     # Runs a single command using the runners shell
#    # - name: Run a one-line script
#     #  run: echo Hello, world!

#     # Runs a set of commands using the runners shell
#     #- name: Run a multi-line script
#      # run: |
#       #  echo Add other actions to build,
#        # echo test, and deploy your project.
